name: Change Verification Record
on:
  workflow_call:
permissions:
  pull-requests: read
jobs:
  ChangeVerificationRecord:
    runs-on: ubuntu-latest
    steps:
      - name: Collect PR data
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const reviews = await github.paginate(
              github.rest.pulls.listReviews,
              { owner, repo, pull_number: pr.number }
            );

            const files = await github.paginate(
              github.rest.pulls.listFiles,
              { owner, repo, pull_number: pr.number }
            );

            const commits = await github.paginate(
              github.rest.pulls.listCommits,
              { owner, repo, pull_number: pr.number }
            );

            const approvals = reviews
              .filter(r => r.state === "APPROVED")
              .map(r => `- ${r.user.login}`)
              .join("\n") || "No approvals";

            core.setOutput("reviews", approvals);
            core.setOutput("files", files.map(f => `- ${f.filename}`).join("\n"));
            core.setOutput(
              "commits",
              commits.map(c => `- ${c.sha.substring(0,7)} ${c.commit.message.split("\n")[0]}`).join("\n")
            );
      - name: Output Change Verification Record
        run: |
          echo "::group::Change Verification Record"
          echo "# Change Verification Record - Jilab Oy"
          echo ""
          echo "**Created at:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          echo "**Change ID:** #${{ github.event.pull_request.number }}"
          echo "**Repository:** ${{ github.repository }}"
          echo "**Branch:** ${{ github.event.pull_request.base.ref }}"
          echo ""
          echo "## Change Description"
          echo "${{ github.event.pull_request.title }}"
          echo ""
          echo "${{ github.event.pull_request.body }}"
          echo ""
          echo "## Author"
          echo "${{ github.event.pull_request.user.login }}"
          echo ""
          echo "## Review & Approval"
          echo "${{ steps.pr.outputs.reviews }}"
          echo ""
          echo "## Files Changed"
          echo "${{ steps.pr.outputs.files }}"
          echo ""
          echo "## Commits"
          echo "${{ steps.pr.outputs.commits }}"
          echo ""
          echo "## Verification"
          echo "Workflow log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo ""
          echo "## Release"
          echo "${{ github.event.pull_request.head.ref }}"
          echo "::endgroup::"